package nz.ac.auckland.se206.controllers;

import java.io.IOException;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.input.MouseEvent;
import javafx.scene.shape.Rectangle;
import nz.ac.auckland.se206.App;
import nz.ac.auckland.se206.classes.Controller;

/** This class is the controller class for the menu scene. */
public class MenuController implements Controller {

  @FXML private Rectangle startRectangle;

  @FXML private Label labelStart; // Reference to StartLabel

  /**
   * Initializes the controller class. This method is automatically called after the fxml file has
   * been loaded.
   */
  @FXML
  public void initialize() {
    System.out.println("MenuController initialized");

    // Add any additional setup here, if needed
    if (startRectangle != null) {
      System.out.println("StartRectangle is initialized.");
    }

    if (labelStart != null) {
      System.out.println("StartLabel is initialized.");
    }
    App.setGameState(App.getContext().getGameStartedState());
  }

  /**
   * This method handles the start button click event.
   *
   * @param event the mouse event
   */
  @FXML
  private void onStartRectangleClick(MouseEvent event) {
    System.out.println("StartRectangle pressed!");
    startGame();
  }

  /**
   * This method handles the start label click event.
   *
   * @param event the mouse event
   */
  @FXML
  private void onStartLabelClick(MouseEvent event) {
    System.out.println("StartLabel pressed!");
    startGame();
  }

  /** This method is called to start the game. */
  private void startGame() {
    System.out.println("Game Starting");
    App.getContext().getGameStartedState().nextState();

    try {
      // Attempt to set the root scene to "room"
      App.setRoot("IntroDialogueScene");
    } catch (IOException e) {
      e.printStackTrace(); // Handle any exception that occurs during the scene change
    }
  }

  /**
   * Runs when ai message has been generated for chat box.
   *
   * @param chat the message generated by the AI
   */
  @Override
  public void onNewChat(String chat) {
    // irrelevant for this controller
  }

  /**
   * This method handles the timer update event.
   *
   * @param time the current time
   */
  @Override
  public void onTimerUpdate(String time) {
    // irrelevant for this controller
  }

  /** This method unlocks the guess button. */
  @Override
  public void unlockGuessBtn() {}
}
